### PR TITLE
Fix more visible connections

### LINKED ISSUE #2966: New connections are hard to see
When creating a new ~~issue~~ atom, suggestions are very visible in the inventory view, but there is little indication that there are new chats available (only a small blue dot on the chats tab). 

If there are already existing and known chats, the notification is good enough to indicate the presence of new messages, but notifications for new chat requests should be at least as visible as suggestions.

chat

^ in this screenshot, there are 2 requested and one active chat connected to the needs shown, but this is not very visible in the interface.

### PR DESCRIPTION
**Pull request by sigpie**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Affected Tests have been added/altered (for bug fixes / features)
- [ ] Docs have been reviewed and added/updated if needed (for bug fixes / features)
- [x] Build was run locally and `mvn install` succeeds

## Pull request type

Please check the type of change your PR introduces:
- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

See #2966 for problem description

## What is the new behavior?

Fixes #2966

- Adds a card that indicates new messages/connection requests for atoms in the inventory
- Connection indicator replaces suggestion indicator if there are unread requests or messages

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-connections-indicator.jsx [hunk 1]
```diff
@@ -14,15 +14,18 @@ import "~/style/_atom-connections-indicator.scss";
...
+  const requestedConnections = atomUtils.getRequestedConnections(atom, state);
   const requestsCount = requestedConnections ? requestedConnections.size : 0;
   const unreadRequests =
     requestedConnections &&
     requestedConnections.filter(conn => conn.get("unread"));
   const unreadRequestsCount = unreadRequests ? unreadRequests.size : 0;
 
   const hasUnreadChatMessages = ownProps && ownProps.hasUnreadChatConnections;
-  const unreadChatConnections = atomUtils.getUnreadChatMessageConnections(atom);
+  const unreadChatConnections = atomUtils.getUnreadChatMessageConnections(
```
Comment (quasarchimaere) [inline webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-connections-indicator.jsx]: i think both methods can be moved to either general or connection selectors, i get that they would fit in the atom utils, but we would probably run into a cyclic dependency that way...
