### PR TITLE
fixed link in post-info and send-request

### LINKED ISSUE #1547: Post-info link in footer should display correct address
The post link shows the resource url, not the userfacing url.

### PR DESCRIPTION
**Pull request by peacememories**
Fixes #1547

### CODE REVIEW

File: webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js [hunk 1]
```diff
@@ -154,7 +154,7 @@ function genComponentConf() {
                         post.get('creationDate')
                     ),
                     createdTimestamp: post && post.get('creationDate'),
-                    linkToPost: post && post.get('uri'), //TODO: MAKE SURE TO CREATE THE CORRET LINK
+                    linkToPost: post && new URL("/owner/#!/post/?postUri="+encodeURI(post.get('uri')), window.location.href).href,
```
Comment (peacememories) [inline webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js]: Remove unnecessary slash
